
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
SET ARITHABORT ON
SET CONCAT_NULL_YIELDS_NULL ON
--SET NUMERIC_ROUNDABORT ON
SET QUOTED_IDENTIFIER ON

USE PSX;
GO

CREATE TABLE dbo.FIPI(
  ID varchar(32) NOT NULL,
  [Date] datetime2(7) NOT NULL,
  GROSS_BUY float NULL,
  GROSS_SELL float NULL,
  NET_BUY_SELL_PKR float NULL,
  NET_BUY_SELL_USD float NULL,
  PRIMARY KEY (ID, [Date])
);
GO

CREATE TABLE dbo.LIPI(
  ID varchar(32) NOT NULL,
  [Date] datetime2(7) NOT NULL,
  GROSS_BUY float NULL,
  GROSS_SELL float NULL,
  NET_BUY_SELL_PKR float NULL,
  NET_BUY_SELL_USD float NULL,
  PRIMARY KEY (ID, [Date])
);
GO
