SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
SET ARITHABORT ON
SET CONCAT_NULL_YIELDS_NULL ON
--SET NUMERIC_ROUNDABORT ON
SET QUOTED_IDENTIFIER ON

USE PSX;
GO

DROP TABLE IF EXISTS FIPI_SECTOR_WISE
GO

CREATE TABLE dbo.FIPI_SECTOR_WISE(
  [CLIENT_TYPE] nvarchar(128) NOT NULL,
  [Date] datetime2(7) NOT NULL,
  [SEC_CODE] nvarchar(128) NOT NULL,
  [SECTOR_NAME] nvarchar(256) NULL,
  [MARKET_TYPE] nvarchar(128) NOT NULL,
  [BUY_VOLUME] float NULL,
  [BUY_VALUE] float NULL,
  [SELL_VOLUME] float NULL,
  [SELL_VALUE] float NULL,
  [NET_VOLUME] float NULL,
  [NET_VALUE] float NULL,
  [USD] float NULL,
  PRIMARY KEY ([CLIENT_TYPE], [Date], [SEC_CODE], [MARKET_TYPE])
);
GO
