USE psx

SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
SET ARITHABORT ON
SET CONCAT_NULL_YIELDS_NULL ON
--SET NUMERIC_ROUNDABORT ON
SET QUOTED_IDENTIFIER ON


select *
from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME='universe'
